apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: my-tls-certificate
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
